{% set version = "4.6.3" %}

package:
  name: lxml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lxml/lxml-{{ version }}.tar.gz
  sha256: 39b78571b3b30645ac77b95f7c69d1bffc4cf8c3b157c435a34da72e78c82468

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - libxml2<=2.9.10
    - python
    - pip
    - cython
    - libxslt
  run:
    - python
    - libxslt

test:
  imports:
    - lxml
    - lxml.etree
    - lxml.objectify
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://lxml.de/
  license: BSD-3-Clause and GPL-2.0-only and ZPL-2.0 and LicenseRef-ElementTree
  license_file: LICENSES.txt
  summary: Pythonic binding for the C libraries libxml2 and libxslt.
  description: |
    The lxml XML toolkit is a Pythonic binding for the C libraries libxml2 and
    libxslt. It is unique in that it combines the speed and XML feature
    completeness of these libraries with the simplicity of a native Python API,
    mostly compatible but superior to the well-known ElementTree API.
  doc_url: http://lxml.de/index.html#documentation
  dev_url: https://github.com/lxml/lxml
  doc_source_url: https://github.com/lxml/lxml/tree/master/doc

extra:
  recipe-maintainers:
    - ocefpaf
